### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by davidcurie** [scholi/pyAvantes#1]
Hello,

Thanks for your existing effort. I found your project useful to me in my efforts to open .RAW8 files. I'd like to make your project a dependency in my project.

Do you have a license you wish to use for this repository?

**Comment by scholi** [comment]
I have it under Apache 2. Is it good for you?

EDIT: Please note that this is good to get the raw data. I don't remember the status in case you need info for the irradiance.

**Comment by davidcurie** [comment]
Apache 2 is great. Thank you.

I made some tweaks to a copy of your file that alter the code slightly to fit the coding style of my existing project. I would like to  include a NOTICE file documenting my changes and listing you as the first author. Would you like me to list your full name or GitHub user name?
